server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 513kesha

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

